### ISSUE TITLE
Organisation of settings panel

### ISSUE THREAD

**Issue by unclej84** [sethvoltz/OctoPrint-DisplayPanel#13]
Hello,

as the base for the settings panel is prepared in #4 and new setting shall be added according to #5 perhaps it would be nice to organize the panel a bit more. I am thinking of tabs "Buttons" and "Display" with following options:

Buttons: Pin GPIO setting, debounce time
Display: display address, rotation, date format, timeout time, timeout selection (timeout on printer disconnected, connected but idle, or always)

The bottom links could then be placed on the related tab.
What do you think about that?

**Comment by Andy-ABTec** [comment]
I'm happy to go with your suggestion for now (and whatever others think), but does the plugin configuration popup actually **need** a title, people should know where they are from the plugin list on the left-hand side of the same popup, and should it be "**_Display Layer Plugin_**" or just "**_Display Plugin_**"? I'm happy with either, but it needs to be consistent - just a couple of thoughts...

**Comment by sethvoltz** [comment]
I just merged the config panel - We can continue here or within a new PR

**Comment by unclej84** [comment]
PR is in preparation. Changed the title to match the name in the plugin list.

**Comment by unclej84** [comment]
This is how it looks with tabs:

![Screenshot 2021-01-03 031504](https://user-images.githubusercontent.com/60842330/103470379-f7dc8680-4d71-11eb-8a65-76d9ca7c3c3f.jpg)
![Screenshot 2021-01-03 031520](https://user-images.githubusercontent.com/60842330/103470380-fd39d100-4d71-11eb-80b3-747d6cb809d9.jpg)

**Comment by Andy-ABTec** [comment]
Nice!

**Comment by Andy-ABTec** [comment]
Sorry, this might be one for @sethvoltz following on from the initial registration, but I've just re-installed the plugin from scratch and noticed that when uninstalled the Plugin Manager calls it the "**OctoPrint Display Panel**", but once it is installed its called "**Display Panel Plugin**" - _confusing_ 🤔

**Comment by Andy-ABTec** [comment]
Talking of confusing - any thoughts about this?
![oops](https://user-images.githubusercontent.com/5175695/103862087-5b3e1f80-50b6-11eb-961d-905ca9a0f2a0.png)

**Comment by Andy-ABTec** [comment]
Looking around I note that some plugins use GPIO.BCM and some use GPIO.BOARD. Is there a preference? Should both be supported (or are they already?) Is it just a matter of personal taste?

Sorry for all the questions, I'm still finding my way around the Pi architecture...

**Comment by sethvoltz** [comment]
Oh no, I hadn’t realized someone had the name first. This started as a hack so I didn’t look too far. I’m open to renaming as I came later. Ideas for a different name?

**Comment by Andy-ABTec** [comment]
Mini Panel, Micro Panel - I don't know, something that infers a small display...

**Comment by sethvoltz** [comment]
Hoping to have some time this weekend to get into this. Mini or Micro Panel has a nice ring to it.

**Comment by unclej84** [comment]
If you could check the tab PR I would directly add the timeout PR (based on the tabs in settings page) - have been testing for around a week now.

**Comment by sethvoltz** [comment]
Sure thing! Laptop is away for the evening but I’ll take a look soon. Thanks for the reminder!

**Comment by sethvoltz** [comment]
@unclej84 or @Andy-ABTec do either of you know if this is sufficient for renaming a plugin? I left the identifier the same so folks don't have to uninstall and reinstall the new version

**Comment by unclej84** [comment]
Sorry, I have no idea how this actually works but I think as you changed the name the overlays feature needs to be used. Best would be to get in contact with Gina or jneilliii

**Comment by Andy-ABTec** [comment]
Likewise, I have no idea...

**Comment by sethvoltz** [comment]
Opened this thread if you want to follow along https://community.octoprint.org/t/how-to-cleanly-rename-an-octoprint-plugin/29155

**Comment by Andy-ABTec** [comment]
Thanks...

**Comment by Andy-ABTec** [comment]
@sethvoltz, not sure if you're aware but OctoPrint isn't offering the 1.2.0 upgrade as available (for me at least, I might be missing something) Plugin Manager says I'm running 1.1.0 - related to the name change maybe?

**Comment by unclej84** [comment]
I got it offered and installed this morning. Have you tried to force an update? Maybe you hit the ratelimit on github?

**Comment by Andy-ABTec** [comment]
I "piped" it over the top of the existing installation and all seems ok, now saying 1.2.0, just wait and see on the next release...

**Comment by sethvoltz** [comment]
I’ve been trying to figure that out myself, I’ve only gotten 1.1.0. I followed all the points from the bootstrap app that were mentioned in the docs so I’m thinking the plugin site periodically polls to see if there’s a newer version and then advertises it?

**Comment by Andy-ABTec** [comment]
Confusing or what... as previously mentioned the only way I got the later version was to force it over the top with pip, might be worth leaving it for a while and then fake a new release just to see what happens.

Other than that I guess it back to Gina or jneilliii...

**Comment by sethvoltz** [comment]
Thanks for the feedback and PRs! I got offered the latest version a few days ago. I'll be cutting a release with the latest changes in a bit, should be notifying folks in a day or two.
