### ISSUE TITLE
[Feature] Progress On Top

### ISSUE THREAD

**Issue by jghake** [sethvoltz/OctoPrint-DisplayPanel#19]
The display on screens with dual color is cut in half.
![2021-01-13 11 52 42](https://user-images.githubusercontent.com/15810575/104506830-c302d780-559a-11eb-9414-4bdfb82a9745.jpg)

**Comment by sethvoltz** [comment]
First off, that green filament is bomb 💣 , where did you get it?

As for the split color, I definitely didn’t design it for use with those. The layout could be modified but you’d likely lose a line of text. Just spitballing, maybe the progress bar would move to the top and three lines could be shown below? I don’t have any plans to do this but if you submit a PR with the layout and a config checkbox, I’ll review it for addition.

**Comment by jghake** [comment]
I don't know much about these but I can/will look in to it eventually. Right now the buttons don't work and I suspect a wiring problem.

This filament is my favorite color. 3DSolutech Camo Green.
https://amazon.com/3D-Solutech-Filament-Dimensional-Accuracy/dp/B07BN8H2LQ/

**Comment by unclej84** [comment]
Maybe this can be realized with an offset to the blocks for top and bottom (e.g. int(bool Switch)*(+/-)offset). That would be easy to handle. Could you provide the information how many pixels the top area has in height (16?)?
Then I will have a look at it and prepare a PR.

**Comment by jghake** [comment]
I tried writing the code myself and all I managed to do was break my code... I'm definitely not a programmer. 

As far as pixel count I guess it's probably 16. My eyes can't see it, and Google has failed me.

**Comment by rbolinger** [comment]
I would love to see a configuration option for progress bar at top or bottom, I have a similar OLED display and would opt to put the progress bar at the top given the choice. And great plugin, amazing job!

Don't know how many pixels the yellow portion is but here is the OLED module on Amazon https://www.amazon.com/gp/product/B072Q2X2LL

**Comment by unclej84** [comment]
The description says 2 rows yellow and 6 rows normale - so 8 Pixels per row makes 16. I can try to make a test version in my repo but cannot test right now - if you could change the files manually for testing afterwards I will do this quickly

**Comment by unclej84** [comment]
is this only relevant for the printing screen or do the other two also need to be altered?

**Comment by jghake** [comment]
I uploaded the files, set the option in the plug-in preferences and rebooted. This is what it looks like now. When I press m the screen changes to the blank bottom, press a few more times and you get the one line chopped off. 

No job
![image](https://user-images.githubusercontent.com/15810575/105566899-6f536500-5ce3-11eb-9d50-131f4160a49f.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105566901-79756380-5ce3-11eb-8434-fdd210aeed1f.jpeg)

Printing
![image](https://user-images.githubusercontent.com/15810575/105566910-85612580-5ce3-11eb-832d-ae5c763dbafc.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105566918-8d20ca00-5ce3-11eb-8bec-d9f3653a0348.jpeg)

**Comment by unclej84** [comment]
I updated the `__init__.py` - the progress bar area cleared too much of the screen. I also made some minor positioning changes to fit the colored area. Could you try again please?

**Comment by unclej84** [comment]
Could you please also check the normal layout with progress bar on bottom (photos would be really helpful) to see if the positioning needs to be different or if it is okay for this too?

**Comment by unclej84** [comment]
Could you please also try `rotation` set and normal layout (if it is okay now)? Would be interesting to see how this would be when having the colored display rotated. A photo would be appreciated.

**Comment by jghake** [comment]
Looks a lot better. 

![image](https://user-images.githubusercontent.com/15810575/105614227-f1dc3300-5d7c-11eb-8b07-797708967b85.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614231-f86aaa80-5d7c-11eb-84d1-2028600d08f4.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614232-fc96c800-5d7c-11eb-87e7-e35e891522cb.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614233-002a4f00-5d7d-11eb-9e57-8d8de3d97e16.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614234-03bdd600-5d7d-11eb-9d9a-d054ccdebbd4.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614235-07e9f380-5d7d-11eb-8a64-e66d52a63a26.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614237-0c161100-5d7d-11eb-9adf-4c21d960ad58.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614241-0fa99800-5d7d-11eb-9b73-1751af503110.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614242-12a48880-5d7d-11eb-8a22-b2beb204aac2.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614245-17693c80-5d7d-11eb-8a26-27860d602231.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614252-2354fe80-5d7d-11eb-8bb2-174f3e3ead28.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614259-28b24900-5d7d-11eb-8b9f-a9ca3a66fab1.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614260-2e0f9380-5d7d-11eb-9b0b-04efe5e03c7b.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614263-3071ed80-5d7d-11eb-99eb-3af27c6fbc44.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614265-32d44780-5d7d-11eb-960a-05f0a6ad0e50.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105614266-3536a180-5d7d-11eb-80be-7ddc5162ab8c.jpeg)

**Comment by unclej84** [comment]
So the progress bar should be 2 pixels higher I guess. Let me check this quickly. Sorry for the confusion regarding rotation - i meant rotation without progress on top - wanted to see if this messes the "normal" layout.

**Comment by jghake** [comment]
Better!

![image](https://user-images.githubusercontent.com/15810575/105615158-54383200-5d83-11eb-8aa2-2e05cb74e93a.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105615162-59957c80-5d83-11eb-953e-27f13a9c6edc.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105615166-5f8b5d80-5d83-11eb-9990-30709d9f27e7.jpeg)
![image](https://user-images.githubusercontent.com/15810575/105615168-61edb780-5d83-11eb-98ff-ab271ad76b45.jpeg)

**Comment by unclej84** [comment]
okay, I made a final tweek because the last line was printed on top - now it should fit. will prepare the PR. If you want you can check the final file before @sethvoltz reviews the PR

**Comment by jghake** [comment]
[perfect](https://media.tenor.com/images/47f86b14d1742ff3531cf0db3b3f9f70/tenor.gif)
![image](https://user-images.githubusercontent.com/15810575/105621250-70a39100-5dba-11eb-9252-9d6a9645433a.jpeg)

**Comment by unclej84** [comment]
Yeah, looks nice. I had another look at your photos with `progress on top` and `rotation` where the last line is cut a bit so I added an additional pixel as offset to move this line completely to the colored area without cutting the top (main branch in my repo + PR here). Think we got it now.

**Comment by sethvoltz** [comment]
Merged in fix, will be cutting a release soon
