### ISSUE TITLE
[Feature] Testing GPIO pin assignment

### ISSUE THREAD

**Issue by Andy-ABTec** [sethvoltz/OctoPrint-DisplayPanel#50]
I've finally got the buttons for my tiny case yesterday (Damm Covid); and I was in the process of wiring everything, running wire in v-slot grooves with snap-in covers etc. when I had an idea...

How about adding a third tab called "Test", or maybe "GPIO Assignment Test" to the plugin configuration page, with nothing on the page but four boxes labelled "Mode", "Cancel", "Play" and "Pause". While the relevant button is pressed the associated box "lights up" (changes colour) and maybe we get beeps identifying which box was activated (1 beep, 2 beeps etc.) for the odd situation when you can't see the screen.

Good as a quick test of GPIO pin assignment and continuity?

**Comment by Andy-ABTec** [comment]
Or you could maybe (probably better) add some form of indicator beside the button assignment drop downs on the first tab, so the assignment could be checked at the same time as testing without having to switch tabs...

**Comment by sethvoltz** [comment]
I dig the idea. I'll leave it open here to see if anyone wants to take it up as a PR.

**Comment by unclej84** [comment]
As far as I understood the documentation this is not possible with the current implementation of the standard template for settings dialog. So one has to create a unique template and some "knockout" code I guess. This is the tricky part - personally I did not understand this whole knockout system.
