### ISSUE TITLE
Enhancement - OLED Display models

### ISSUE THREAD

**Issue by Andy-ABTec** [sethvoltz/OctoPrint-DisplayPanel#6]
Hi @sethvoltz - apologies back again...
 
Whilst I was really impressed with your case design, unfortunately, it doesn't fit my needs and I started rummaging around on the internet looking for drawings for the display.

Eventually, I found one and from that, I created basic Fusion 360 and STEP models which I've attached here. Please feel free to include them in the project if you wish.

With regard to a PR for a Configuration Page, I'll have a go but at the moment I'm working my way through @foosel's tutorial in the vain hope of understanding what's going on with plugins!
![OLED Display Mechanical Drawing](https://user-images.githubusercontent.com/5175695/102790392-46b31500-439d-11eb-8dac-bd1554ddee70.jpg)

**Comment by bluespaniel** [comment]
Thank you, that is very useful.

**Comment by Andy-ABTec** [comment]
PLEASE DELETE THIS _ THERE'S OBVIOUSLY MORE THAN ONE SIZE OF 0.96" BOARD - Taking of boards, back to the drawing board, well Fusion anyway...

**Comment by Andy-ABTec** [comment]
PLEASE IGNORE THIS ISSUE - DRAWING OF SLIGHTLY DIFFERENT SIZED BOARD...
