### ISSUE TITLE
Support for different resolution possible?

### ISSUE THREAD

**Issue by ventilator** [sethvoltz/OctoPrint-DisplayPanel#73]
Are there any plans  to support or to config even smaller displays?
e.g. I have this display http://www.esp8266learning.com/wemos-oled-shield-example.php
Screen Size: 64×48 pixels
Does not make much sense, probably, to use such tiny resolution?
Result is this:
![image](https://user-images.githubusercontent.com/4276067/120025597-33ae0c00-bff1-11eb-9189-5377bb05d815.png)

**Comment by sethvoltz** [comment]
No plans for it, no. The displays are so cheap (I think it was $2 a piece for a small pack on Amazon) and anything smaller would be a challenge to fit anything useful on it. 

That said, if you have a particular need for the smaller display, feel free to open a PR and I’ll review it.
